[tool.poetry]
name = "python-bcb"
version = "0.3.0"
description = ""
authors = ["wilsonfreitas <wilson.freitas@gmail.com>"]
readme = "README.md"
packages = [{include = "bcb"}]

[tool.poetry.dependencies]
python = ">= 3.10"
httpx = ">= 0.24.0"
lxml = ">= 4.9.2"
pandas = ">= 2.0.0"
requests = ">= 2.31.0"

[tool.poetry.group.test.dependencies]
pytest = ">= 7.1.3"
flaky = ">= 3.7.0"

[tool.poetry.group.docs.dependencies]
Sphinx = "^6"
pydata-sphinx-theme = ">= 0.10.1"
matplotlib = ">= 3.5.3"
ipython = ">= 8.14.0"
furo = ">= 2022.6.21"
pickleshare = "^0.7.5"

[tool.poetry.group.dev.dependencies]
pycodestyle = ">= 2.9.1"
ipykernel = ">= 6.15.2"
black = {version = ">= 22.8.0", allow-prereleases = true}
jupyter = "^1.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
