[tool.poetry]
name = "python-bcb"
version = "0.1.8"
description = ""
authors = ["wilsonfreitas <wilson.freitas@gmail.com>"]
readme = "README.md"
packages = [{include = "bcb"}]

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.23.0"
lxml = "^4.9.1"
pandas = "^1.4.4"
requests = "^2.28.1"

[tool.poetry.group.test.dependencies]
pytest = "^7.1.3"

[tool.poetry.group.docs.dependencies]
Sphinx = "^5.1.1"
pydata-sphinx-theme = "^0.10.1"
matplotlib = "^3.5.3"
ipython = "^8.5.0"
furo = "^2022.6.21"


[tool.poetry.group.dev.dependencies]
pycodestyle = "^2.9.1"
ipykernel = "^6.15.2"
black = {version = "^22.8.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
